### ISSUE TITLE
Add reference to ChaCha plugin in Wikipedia

### ISSUE THREAD

**Issue by ekzyis** [ekzyis/CrypTool-2#14]
> 9) Bekanntmachen
> 
> ...
> 
> b) In Wikipedia könnten Sie bei
 https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant
entweder eine Referenz zu Ihrer Visualisierung ergänzen,
oder den Verweis dazu unter "External Links" aufnehmen.

**Comment by ekzyis** [comment]
@be4 I added a link to my bachelor thesis under "External links" now. See https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant

Is this how you imagined this? Not sure how I should interpret

> Referenz zu Ihrer Visualisierung

**Comment by be4** [comment]
Yes, fine with me.
Your thesis and the according visualization can help people to 
understand the inner workings of ChaCha better/easier.

Best regards, BE

Am 25.12.2021 um 00:55 schrieb Ramdip Gill:
> @be4 I added a link to my bachelor thesis under "External links" now. See https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant
>
> Is this how you imagined this? Not sure how I should interpret
>
>> Referenz zu Ihrer Visualisierung
